### ISSUE TITLE
Proposal Checklist

### ISSUE THREAD

**Issue by juliawang105** [umnum/Eventbriter#1]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [ ] Correctly formatted
    - [ ] each wiki page is listed in bullet points
    - [ ] all links route the correct page

## Comments

---

# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [ ] The other 4 are from the [MVP List](https://open.appacademy.io/learn/swe-in-person/full-stack-project/mvp-checklist) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

## Comments
*Tickets need to be created when events are created 
* Event creation is your full CRUD right?
*Search/GoogleMaps will be bonus features 
---

# Database Schema

- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

## Comments
* Event should have a category_id not the other way around 
* Consider having a separate categories table and a joins table for events and categories: many to many relationships 
* Capacity for an event can also live on the tickets table

---

# Sample State

- [ ] State shape is flat!
- [ ] State's keys are camelCased
- [ ] All keys within the values in the state are accessible in the schema
- [ ] Correctly formatted
    - [ ] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [ ] Top level slices
        - [ ] `entities`
        - [ ] `session`
        - [ ] `errors` (here or in `ui`)
        - [ ] `ui` (if needed)
    - [ ] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments

---

# Backend Routes

- [ ] Contains the following sections: HTML, API Endpoints(Backend)
- [ ] Each route has a description
- [ ] API Endpoint routes contains wildcard variables written in `snake_case`
- [ ] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [ ] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

## Comments

---

# Frontend Routes

- [ ] Frontend routes contains wildcard variables written in `camelCase`
- [ ] Correctly formatted
    - [ ] Routes are displayed with `inline coding text` (backticks)

**Comment by juliawang105** [comment]
See comments for mvps and schema

**Comment by umnum** [comment]
I think I need to get rid of the categories table entirely, since I only have a fixed set of categories to choose from. I tried to create an event on Eventbrite and it forced me to choose only one out of 21 categories. I also need to pick a `type` for the event as well, which is similar to category. Should I just add `type` and `event` as `string`s in a column for the event table? There is also a `tags` feature which allows me to input at most 10 words, which are 25 characters max. These `tags` allow me to search for events by their keywords. I was thinking of adding a `keywords` table and a joins table called `tags` for `keywords` and `events`, because an event can have many tags and a tag can have many events.  Also, there would be an index on `[:keyword_id, :event_id], unique: true` in the `tags` table, since an event cannot have multiple of the same keywords. Am I wrong in restructuring the schema this way?

**Comment by umnum** [comment]
actually ... after further research, the `type` column is already represented as my `format` column in my `events` table ... I'll switch `format` to `type` because `type` is a better description

**Comment by juliawang105** [comment]
* Yes- change the `format` to `type`.
* Yes-create a `keywords` table and a `tags` joins table 
* as for the `categories` you want a `categories` table and a foreign_key on the `events` table  because you can later display events by category. You won't need to `edit` or `update` or `destroy` anything in the `categories` table. It will always just stay at 21 elements.
* after adding those changes to your schema, update you sample state
